language: cpp
compiler: g++

dist: trusty

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq premake4 gcc gcc-multilib libc6-dev-i386 g++ g++-multilib

before_script:
  - $CXX --version
  - premake4 gmake

script:
  - make config=release32

addons:
  artifacts:
    paths:
    - $(ls bin/*.so | tr "\n" ":")
