version: {branch}-b{build}
os: Visual Studio 2015

configuration:
  - Release

install:
    - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

build_script:
  - ps: .\build.ps1 -Target "AppVeyor"

test: off
